// <auto-generated />
using System;
using FAQBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FAQBot.Migrations
{
    [DbContext(typeof(FAQDB))]
    [Migration("20221107133838_LackeyApplications")]
    partial class LackeyApplications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FAQBot.Models.FAQEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("FAQBot.Models.FAQTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FAQEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FAQEntryId");

                    b.ToTable("FAQsTags");
                });

            modelBuilder.Entity("FAQBot.Models.LackeyApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ApplicantId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("ApplicationTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LackeyApplications");
                });

            modelBuilder.Entity("FAQBot.Models.LackeyApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Approver")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("LackeyApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LackeyApplicationId");

                    b.ToTable("LackeyApprovals");
                });

            modelBuilder.Entity("FAQBot.Models.FAQTag", b =>
                {
                    b.HasOne("FAQBot.Models.FAQEntry", "FAQEntry")
                        .WithMany("Tags")
                        .HasForeignKey("FAQEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FAQEntry");
                });

            modelBuilder.Entity("FAQBot.Models.LackeyApproval", b =>
                {
                    b.HasOne("FAQBot.Models.LackeyApplication", null)
                        .WithMany("Approvals")
                        .HasForeignKey("LackeyApplicationId");
                });

            modelBuilder.Entity("FAQBot.Models.FAQEntry", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FAQBot.Models.LackeyApplication", b =>
                {
                    b.Navigation("Approvals");
                });
#pragma warning restore 612, 618
        }
    }
}
